### ISSUE TITLE
No tvOS target in iOS project...?

### ISSUE THREAD

**Issue by bohlec** [abdullahceylan/expo-template-bare-minimum-tvos#2]
Hi!

I have an existing bare Expo project that I'm trying to add tvOS support to. Since the prebuild command isn't really an option in my setup, I was trying to use this repo as a guide on how to properly set up the iOS project.

After installing, pod installing and opening the project in XCode - I don't see a new tvOS target, and I don't see tvOS added as a Supported Destination for the only target available. 

If I add tvOS as a destination to the existing target and attempt to build and deploy to an Apple TV Simulator, I get build errors:

<img width="537" alt="image" src="https://user-images.githubusercontent.com/1735896/207723780-37cb8328-8211-4ac9-a1a9-7012767441d9.png">

If I try and build to an iPhone 14 simulator, I get build errors:

<img width="532" alt="image" src="https://user-images.githubusercontent.com/1735896/207723639-70b70538-9b4d-4d4c-a306-8f81fe6c1dc0.png">

I'm new to Expo and React Native (and XCode for that matter) so I might be misunderstanding something, but how can I get this working so I can try and replicate in my application?

Thank you!

**Comment by abdullahceylan** [comment]
Hi @bohlec,
According to the errors, there are some missing packages. Firstly, did you change the `react-native` version as `npm:react-native-tvos@0.69.6-0`? Since TV functionality has been removed from the core package, this is required.

Also, you need to install `expo-keep-awake` and `expo-modules-core` packages according to the first error.

I'm not sure if you can push your sample project to somewhere I can pull, I can also have a look when I'm available.

Thanks.

**Comment by bohlec** [comment]
Hi @abdullahceylan - thanks for the response. I managed to get things working for my application with the exception of `expo-updates` which wasn't as simple as updating the build targets in the podspec. You don't have a working patch for that package by chance, do you?

**Comment by abdullahceylan** [comment]
Hey @bohlec - Sorry for the late reply. Unfortunately, I haven't tried `expo-updates` with this template. I don't think I can do it anytime soon. I'll close the issue as the actual issue has been solved already but will update my comment when I find a chance to try with `expo-updates`.

Thanks.
